SELECT dblink_connect('myconn', 'dbname=bvhaiphong port=5432 host=179.84.31.5 user=postgres password=haiphong1234');



INSERT INTO vienphi
SELECT tbluser.*
FROM dblink('myconn','select * FROM vienphi where vienphidate>=''2018-01-01 00:00:00''')
    AS tbluser(vienphiid integer,
  vienphicode text,
  loaivienphiid integer,
  vienphistatus integer,
  departmentgroupid integer,
  departmentid integer,
  hosobenhanid integer,
  doituongbenhnhanid integer,
  dathutienkham integer,
  dagiuthebhyt integer,
  bhytid integer,
  patientid integer,
  vienphidate timestamp without time zone,
  vienphidate_ravien timestamp without time zone,
  chandoanvaovien text,
  chandoanvaovien_code text,
  chandoanravien text,
  chandoanravien_code text,
  chandoanravien_kemtheo text,
  chandoanravien_kemtheo_code text,
  bhyt_traituyen double precision,
  bhyt_thangluongtoithieu double precision,
  bhyt_gioihanbhyttrahoantoan double precision,
  duyet_ngayduyet timestamp without time zone,
  duyet_nguoiduyet integer,
  duyet_sothutuduyet integer,
  vienphistatus_bh integer,
  duyet_ngayduyet_bh timestamp without time zone,
  duyet_nguoiduyet_bh integer,
  duyet_sothutuduyet_bh integer,
  vienphistatus_vp integer,
  duyet_ngayduyet_vp timestamp without time zone,
  duyet_nguoiduyet_vp integer,
  duyet_sothutuduyet_vp integer,
  vienphistatus_tk integer,
  duyet_ngayduyet_tk timestamp without time zone,
  duyet_nguoiduyet_tk integer,
  duyet_sothutuduyet_tk integer,
  tongtiendichvu double precision,
  tongtiendichvu_bh double precision,
  tongtiendichvu_dv double precision,
  tongtiendichvu_bhyt double precision,
  tongtienmiengiam double precision,
  tongtiendatra double precision,
  tongtiendatra_bh double precision,
  tongtiendatra_dv double precision,
  tongtiendatra_tk double precision,
  isneedupdatemoney integer ,
  isneedupdateinfo integer ,
  money_khambenh double precision,
  money_xetnghiem double precision,
  money_chandoanhinhanh double precision,
  money_thamdochucnang double precision,
  money_thuoctrongdanhmuc double precision,
  money_thuocngoaidanhmuc double precision,
  money_mauchephammau double precision,
  money_phauthuatthuthuat double precision,
  money_vattutrongdanhmuc double precision,
  money_vattutrongdanhmuctt double precision,
  money_vattungoaidanhmuc double precision,
  money_dichvukythuatcao double precision,
  money_thuocungthungoaidanhmuc double precision,
  money_ngaygiuongchuyenkhoa double precision,
  money_vanchuyen double precision,
  money_phuthu double precision,
  money_dv_khambenh double precision,
  money_dv_xetnghiem double precision,
  money_dv_chandoanhinhanh double precision,
  money_dv_thamdochucnang double precision,
  money_dv_thuoctrongdanhmuc double precision,
  money_dv_thuocngoaidanhmuc double precision,
  money_dv_mauchephammau double precision,
  money_dv_phauthuatthuthuat double precision,
  money_dv_vattutrongdanhmuc double precision,
  money_dv_vattutrongdanhmuctt double precision,
  money_dv_vattungoaidanhmuc double precision,
  money_dv_dichvukythuatcao double precision,
  money_dv_thuocungthungoaidanhmuc double precision,
  money_dv_ngaygiuongchuyenkhoa double precision,
  money_dv_vanchuyen double precision,
  money_dv_phuthu double precision,
  lastaccessdate timestamp without time zone,
  vienphiremark text,
  version timestamp without time zone,
  duyet_quyduyet text,
  vienphidate_noitru timestamp without time zone,
  medicalrecordid_start integer,
  medicalrecordid_end integer,
  sync_flag integer,
  update_flag integer,
  datronvien integer,
  departmentgroupid_start integer,
  departmentid_start integer,
  bhyt_tuyenbenhvien integer,
  masothue text,
  sotaikhoan text,
  userdangkythebhyt integer,
  thoigiandangkythe timestamp without time zone,
  userhuydangkythebhyt integer,
  vienphidate_ravien_update timestamp without time zone,
  lydohuyduyetketoan text,
  theghep_bhytcode text,
  theghep_bhytfromdate timestamp without time zone,
  theghep_bhytutildate timestamp without time zone,
  theghep_macskcbbd text,
  theghep_du5nam6thangluongcoban integer,
  theghep_dtcbh_luyke6thang integer,
  theghep_noisinhsong text);
  
  
  
-- Table: bhyt
INSERT INTO bhyt
SELECT tbluser.*
FROM dblink('myconn','select * FROM bhyt where bhytdate>=''2018-01-01 00:00:00''')
    AS tbluser(bhytid serial integer,
  patientid integer,
  hosobenhanid integer,
  medicalrecordid integer,
  vienphiid integer,
  bhytcode text,
  macskcbbd text,
  bhytdate timestamp without time zone,
  bhytfromdate timestamp without time zone,
  bhytutildate timestamp without time zone,
  bhyt_loaiid integer,
  thuongbinhdieutritaiphat integer,
  thamgiabhytdu36thang integer,
  imagedata bytea,
  imagesize integer,
  bhytremark text,
  lastaccessdate timestamp without time zone,
  version timestamp without time zone,
  dongbaohiemlientuc150ngay integer,
  sync_flag integer,
  update_flag integer,
  isencript integer,
  noisinhsong text,
  du5nam6thangluongcoban integer,
  dtcbh_luyke6thang integer,
  bhytcheckstatus integer,
  stt_dkbhyt text,
  bhyt_miencungchitra timestamp without time zone,
  theghep_bhytcode text,
  theghep_bhytfromdate timestamp without time zone,
  theghep_bhytutildate timestamp without time zone,
  theghep_miencungchitra timestamp without time zone,
  theghep_macskcbbd text,
  theghep_du5nam6thangluongcoban integer,
  theghep_dtcbh_luyke6thang integer,
  theghep_noisinhsong text
);  
  
-- Table: bill
INSERT INTO bill
SELECT tbluser.*
FROM dblink('myconn','select * FROM bill where billdate>=''2018-01-01 00:00:00''')
    AS tbluser(billid integer,
  billcode text,
  billgroupcode text,
  medicalrecordid integer,
  patientid integer ,
  vienphiid integer ,
  listmaubenhphamid text,
  hosobenhanid integer ,
  loaiphieuthuid integer,
  billmode integer,
  userid integer ,
  billdate timestamp without time zone,
  departmentgroupid integer,
  departmentid integer,
  tongtien double precision,
  chietkhau double precision,
  datra double precision,
  conno double precision,
  conno_henthanhtoan timestamp without time zone,
  patientname text,
  dahuyphieu integer,
  billid_ketchuyenam integer,
  billid_ketchuyenduong integer,
  isyeucau integer,
  thoigianhuyphieu timestamp without time zone,
  lydohuyphieu text,
  billremark text,
  printremark text,
  version timestamp without time zone,
  miengiam text,
  lydomiengiam text,
  useridhuyphieu integer,
  sync_flag integer,
  update_flag integer,
  hinhthucthanhtoan integer,
  tracenumber integer,
  pos_billcode text,
  imei text,
  hinhthucthanhtoanhuy integer,
  isencript integer,
  nguonhachtoan integer,
  khoachuyenden integer,
  phonghachtoan integer,
  danhsachdoituongdichvu text,
  iskhac integer
);


-- Table: billaccountdate
INSERT INTO billaccount
SELECT tbluser.*
FROM dblink('myconn','select * FROM billaccount where billaccountdate>=''2018-01-01 00:00:00''')
    AS tbluser(
  billaccountid integer,
  billaccountrefcode text,
  billaccountremark text,
  billaccountrefid integer ,
  billid integer ,
  patientid integer ,
  vienphiid integer ,
  isyeucau integer ,
  billaccountdate timestamp without time zone,
  tongsotien double precision,
  version timestamp without time zone,
  sync_flag integer,
  update_flag integer,
  iskhac integer
);



-- Table: hosobenhan
INSERT INTO hosobenhan
SELECT tbluser.*
FROM dblink('myconn','select * FROM hosobenhan where hosobenhandate>=''2018-01-01 00:00:00''')
    AS tbluser(
  hosobenhanid integer,
  soluutru text,
  soluutru_remark text,
  soluutru_vitri text,
  soluutru_nguoiluu integer,
  hosobenhancode text,
  isuploaded integer,
  isdownloaded integer,
  loaibenhanid integer,
  userid integer,
  departmentgroupid integer,
  departmentid integer,
  hinhthucvaovienid integer,
  ketquadieutriid integer,
  xutrikhambenhid integer,
  hinhthucravienid integer,
  hosobenhanstatus integer,
  patientid integer,
  hosobenhandate timestamp without time zone,
  hosobenhandate_ravien timestamp without time zone,
  chandoanvaovien_code text,
  chandoanvaovien text,
  chandoanravien_code text,
  chandoanravien text,
  chandoanravien_kemtheo_code text,
  chandoanravien_kemtheo text,
  lastaccessdate timestamp without time zone,
  hosobenhanremark text,
  version timestamp without time zone,
  sovaovien text  ,
  patientname text,
  birthday timestamp without time zone,
  birthday_year integer,
  gioitinhcode text,
  nghenghiepcode text,
  hc_dantoccode text,
  hc_quocgiacode text,
  hc_sonha text,
  hc_thon text,
  hc_xacode text,
  hc_huyencode text,
  hc_tinhcode text,
  noilamviec text,
  nguoithan text,
  nguoithan_name text,
  nguoithan_phone text,
  nguoithan_address text,
  gioitinhname text,
  nghenghiepname text,
  hc_dantocname text,
  hc_quocgianame text,
  hc_xaname text,
  hc_huyenname text,
  hc_tinhname text,
  sync_flag integer,
  update_flag integer,
  patient_id text,
  imagedata bytea,
  imagesize integer ,
  patientcode text,
  soluutru_thoigianluu timestamp without time zone,
  isencript integer,
  ismocapcuu integer,
  bhytcode text,
  malifegap text,
  bhytcheckstatus integer,
  matainan integer,
  cannang double precision,
  thoigianmotran timestamp without time zone,
  userthuchienmotranbhyt integer,
  usermotranbhyt integer,
  lydomotranbhyt text,
  nguoithan_cmnn_cccd text
)



-- Table: maubenhpham
INSERT INTO maubenhpham
SELECT tbluser.*
FROM dblink('myconn','select * FROM maubenhpham where maubenhphamdate>=''2018-01-01 00:00:00''')
    AS tbluser(maubenhphamid integer,
  medicalrecordid integer  ,
  patientid integer  ,
  vienphiid integer  ,
  hosobenhanid integer  ,
  dathutien integer  ,
  datamung integer  ,
  servicepriceid_master integer  ,
  phieudieutriid integer  ,
  sothutuid integer  ,
  sothutunumber integer  ,
  sothutunumberdagoi integer  ,
  sothutuid_laymau integer  ,
  sothutunumber_laymau integer  ,
  sothutunumberdagoi_laymau integer  ,
  medicinestoreid integer  ,
  departmentgroupid integer  ,
  departmentid integer  ,
  buonggiuong text,
  userid integer  ,
  departmentgroupid_des integer  ,
  departmentid_des integer  ,
  departmentid_des_org integer  ,
  departmentid_laymau integer  ,
  medicinestorebillid integer  ,
  sophieu text,
  barcode text,
  maubenhphamtype integer  ,
  maubenhphamhaophi integer  ,
  maubenhphamphieutype integer  ,
  maubenhphamgrouptype integer  ,
  maubenhphamdatastatus integer  ,
  maubenhphamstatus_laymau integer  ,
  maubenhphamprintstatus integer  ,
  maubenhphamstatus integer  ,
  maubenhphamdate timestamp without time zone,
  maubenhphamdate_sudung timestamp without time zone,
  maubenhphamdate_thuchien timestamp without time zone,
  maubenhphamdate_laymau timestamp without time zone,
  maubenhphamfinishdate timestamp without time zone,
  unmapedhisservice text,
  isdeleted integer  ,
  maubenhphamdeletedate timestamp without time zone,
  userdelete text,
  usercreate text,
  userupdatebarcode text,
  userlastupdate text,
  userupdatebarcodedate timestamp without time zone,
  userlastupdatedate timestamp without time zone,
  patientpid text,
  doituong text,
  patientname text,
  patientaddress text,
  patientphone text,
  patientbirthday timestamp without time zone,
  patientsex integer,
  chandoan text,
  remark text,
  version timestamp without time zone,
  userduyetall integer  ,
  usertrakq integer  ,
  ismaubenhphamtemp integer  ,
  sothutuphongkhamid integer  ,
  userthuchien integer,
  thoigiandukiencoketqua timestamp without time zone,
  sodienthoaibaotinkhicoketqua text,
  sync_flag integer,
  update_flag integer,
  dacodichvuthutien integer,
  dacodichvuduyetcanlamsang integer,
  sessionid integer  ,
  isautongaygiuong integer,
  sothutuchidinhcanlamsang integer,
  isencript integer,
  maubenhphamdate_org timestamp without time zone,
  departmentid_traketqua integer,
  numbertraketqua integer,
  isdatraketqua integer,
  usertraketqua integer,
  maubenhphamtraketquadate timestamp without time zone,
  remarkdetail text,
  chandoan_code text,
  hl7_is integer,
  hl7_isdatraketqua integer,
  hl7_maubenhphamtraketquadate timestamp without time zone,
  loidanbacsi text,
  phieutonghopsuatanid integer,
  medicinekiemkeid integer,
  isloaidonthuoc integer,
  servicepriceid_thanhtoanrieng integer,
  sothutunumber_h_n integer,
  userlaymau integer,
  dm_loaibenhphamcode text,
  maubenhphamtype_capcuu integer
)



-- Table: medicalrecord
INSERT INTO medicalrecord
SELECT tbluser.*
FROM dblink('myconn','select * FROM medicalrecord where thoigianvaovien>=''2018-05-01 00:00:00''')
    AS tbluser(
  medicalrecordid integer,
  medicalrecordcode text,
  sothutuid integer,
  sothutunumber integer,
  sothutuphongkhamid integer,
  sothutuphongkhamnumber integer,
  vienphiid integer,
  hosobenhanid integer ,
  medicalrecordid_next integer ,
  medicalrecordid_master integer,
  medicalrecordstatus integer,
  departmentgroupid integer,
  departmentid integer,
  giuong text,
  loaibenhanid integer,
  userid integer,
  patientid integer,
  doituongbenhnhanid integer,
  bhytid integer,
  lydodenkham text,
  yeucaukham text,
  thoigianvaovien timestamp without time zone,
  chandoanvaovien text,
  chandoanvaovien_code text,
  chandoanvaovien_kemtheo text,
  chandoanvaovien_kemtheo_code text,
  chandoankkb text,
  chandoankkb_code text,
  chandoanvaokhoa text,
  chandoanvaokhoa_code text,
  chandoanvaokhoa_kemtheo text,
  chandoanvaokhoa_kemtheo_code text,
  isthuthuat integer,
  isphauthuat integer,
  hinhthucvaovienid integer,
  backdepartmentid integer,
  uutienkhamid integer,
  noigioithieuid integer,
  vaoviencungbenhlanthu integer,
  thoigianravien timestamp without time zone,
  chandoanravien text,
  chandoanravien_code text,
  chandoanravien_kemtheo text,
  chandoanravien_kemtheo_code text,
  chandoanravien_kemtheo1 text,
  chandoanravien_kemtheo_code1 text,
  chandoanravien_kemtheo2 text,
  chandoanravien_kemtheo_code2 text,
  xutrikhambenhid integer,
  hinhthucravienid integer,
  ketquadieutriid integer,
  nextdepartmentid integer,
  nexthospitalid integer,
  istaibien integer,
  isbienchung integer,
  giaiphaubenhid integer ,
  lydovaovien text,
  vaongaythucuabenh integer,
  quatrinhbenhly text,
  tiensubenh_banthan text,
  tiensubenh_giadinh text,
  khambenh_toanthan text,
  khambenh_mach text,
  khambenh_nhietdo text,
  khambenh_huyetap_low text,
  khambenh_huyetap_high text,
  khambenh_nhiptho text,
  khambenh_cannang text,
  khambenh_chieucao text,
  khambenh_vongnguc text,
  khambenh_vongdau text,
  khambenh_bophan text,
  tomtatkqcanlamsang text,
  chandoanbandau text,
  daxuly text,
  tomtatbenhan text,
  chandoankhoakhambenh text,
  daxulyotuyenduoi text,
  medicalrecordremark text,
  lastaccessdate timestamp without time zone,
  version timestamp without time zone,
  chandoantuyenduoi text,
  chandoantuyenduoi_code text,
  noigioithieucode text,
  canlamsangstatus integer,
  sync_flag integer,
  update_flag integer,
  lastuserupdated integer,
  lasttimeupdated timestamp without time zone,
  keylock integer,
  cv_chuyenvien_hinhthucid integer,
  cv_chuyenvien_lydoid integer,
  cv_chuyendungtuyen integer,
  cv_chuyenvuottuyen integer,
  xetnghiemcanthuchienlai text,
  loidanbacsi text,
  chandoanbandau_code text,
  nextbedrefid integer,
  nextbedrefid_nguoinha text,
  thoigianchuyenden timestamp without time zone,
  khambenh_thilucmatphai text,
  khambenh_thilucmattrai text,
  khambenh_klthilucmatphai text,
  khambenh_klthilucmattrai text,
  khambenh_nhanapmatphai text,
  khambenh_nhanapmattrai text,
  chandoantuyenduoikemtheo text,
  chandoantuyenduoikemtheo_code text,
  chandoanravien_phanbiet text,
  chandoanravien_phanbiet_code text
)




-- Table: medicine
INSERT INTO medicine
SELECT tbluser.*
FROM dblink('myconn','select * FROM medicine where medicinedate>=''2018-05-01 00:00:00''')
    AS tbluser(medicineid integer,
  medicineperiodid integer ,
  medicinestorerefid integer,
  medicinerefid integer,
  medicinestoreid integer,
  medicinestorebillid integer,
  medicinestorebillcode text,
  medicinestorebilltype integer,
  medicinestorebillstatus integer,
  bill_mode integer,
  ngaysudungthuoc timestamp without time zone,
  partnerid integer,
  medicinestorebillremark text,
  departmentgroupid integer,
  departmentid integer,
  solo text,
  sodangky text,
  hansudung timestamp without time zone,
  xuat_vat double precision,
  xuat_giaban double precision,
  medicinedate timestamp without time zone,
  soluong double precision,
  sodukhadungupdated double precision,
  money double precision,
  vat double precision,
  approve_medicinedate timestamp without time zone,
  approve_soluong double precision,
  approve_money double precision,
  approve_vat double precision,
  accept_medicinedate timestamp without time zone,
  accept_soluong double precision,
  accept_money double precision,
  accept_vat double precision,
  finish_medicinedate timestamp without time zone,
  finish_soluong double precision,
  finish_money double precision,
  finish_vat double precision,
  isremove integer,
  servicepriceid integer,
  listservicepriceid text,
  medicineremark text,
  medicinelinhthuocremark text,
  version timestamp without time zone,
  isphieubuthieu integer,
  sync_flag integer,
  update_flag integer,
  medicinekiemkeid integer,
  hansudung_year integer,
  hansudung_month integer,
  goithau text,
  nguonchuongtrinhid integer,
  userid integer,
  medicinekiemkeid_parter integer,
  stt_dauthau text,
  quyetdinhtrungthau text,
  namcungung text
)


-- Table: medicine_store_bill
INSERT INTO medicine_store_bill
SELECT tbluser.*
FROM dblink('myconn','select * FROM medicine_store_bill where medicinestorebilldate>=''2018-05-01 00:00:00''')
    AS tbluser(medicinestorebillid integer,
  medicineperiodid integer ,
  medicinestoreid integer,
  medicinestorebillid_yc integer,
  medicinestorebillid_im integer,
  medicinestorebillid_ex integer,
  sochungtu text,
  linkcode text,
  isxuattutruc integer,
  partnerid integer,
  partnername text,
  customername text,
  medicinestorebillcode text,
  medicinestorebilldate timestamp without time zone,
  medicinestorebilldoer text,
  medicinestorebilltype integer,
  medicinestorebillstatus integer,
  medicinestorebillfinisheddate timestamp without time zone,
  datatype integer,
  loaithuoc integer,
  isdaduyetphieu integer,
  medicinestorebillapprover text,
  medicinestorebillapprovemessage text,
  medicinestorebillapprovedate timestamp without time zone,
  isdayeucau integer,
  medicinestorebillprocessinger text,
  medicinestorebillprocessingmessage text,
  medicinestorebillprocessingdate timestamp without time zone,
  isremove integer,
  nguoihuyphieu text,
  lydohuyphieu text,
  ngayhuyphieu timestamp without time zone,
  isdathutien integer,
  nguoithutien text,
  lydothutien text,
  ngaythutien timestamp without time zone,
  sothutien double precision,
  medicinestorebillremark text,
  medicinestorebilltotalmoney double precision,
  medicinestorebillphaitramoney double precision,
  medicinestorebilldatramoney double precision,
  medicinestorebillconnomoney double precision,
  medicinestorebilldatemoney timestamp without time zone,
  medicinestorebillchietkhau double precision,
  medicinestorebillthuegtgt double precision,
  ketoanduocid integer,
  listdonthuoc text,
  bill_mode integer,
  lanin integer,
  maubenhphamid integer,
  departmentgroupid integer,
  departmentid integer,
  ngaysudungthuoc timestamp without time zone,
  lanlinhthuoctrongngay integer,
  ylenhlinhthuoc text,
  version timestamp without time zone,
  isphieubuthieu integer,
  lastuserupdated integer,
  lasttimeupdated timestamp without time zone,
  sync_flag integer,
  update_flag integer,
  sothutunumber integer,
  soquaynumber integer,
  iscangoiloa integer,
  ngaychungtu timestamp without time zone,
  keylock integer,
  medicinekiemkeid integer,
  ngayylenh text,
  isbusy integer ,
  sothuthuphongluu text,
  bacsi text,
  chandoan text,
  medicinekiemkeid_parter integer,
  bacsi_id integer,
  khoa_id integer,
  phong_id integer,
  iskhovattubanle integer,
  billgroupid integer,
  billgroupcode text,
  billcode text
)

-- Table: service
INSERT INTO service
SELECT tbluser.*
FROM dblink('myconn','select * FROM service where servicedate>=''2018-05-01 00:00:00''')
    AS tbluser(serviceid integer,
  hosobenhanid integer,
  medicalrecordid integer,
  maubenhphamid integer,
  servicepriceid integer,
  servicepricecode text,
  servicecode text,
  servicename text,
  servicevalue text,
  servicedate timestamp without time zone,
  servicestatus integer,
  servicedoer text,
  servicecomment text,
  soluong double precision,
  serviceresult text,
  studyinstuid text,
  isdeleted integer ,
  servicedeletedate timestamp without time zone,
  userdelete text,
  usercreate text,
  version timestamp without time zone,
  vienphiid integer,
  servicevalueexcel bytea,
  servicevalueexcelreportid integer,
  sync_flag integer,
  update_flag integer,
  servicetimetrakq timestamp without time zone,
  serviceusertrakq text,
  serviceremark1 text,
  serviceremark2 text,
  vitrisinhthiet text,
  somanhsinhthiet text,
  idmayxn integer,
  tenmayxn text,
  ketquanhanxet text)
  
  
-- Table: serviceprice
INSERT INTO serviceprice
SELECT tbluser.*
FROM dblink('myconn','select * FROM serviceprice where servicepricedate>=''2018-03-01 00:00:00''')
    AS tbluser(servicepriceid integer,
  medicalrecordid integer,
  vienphiid integer ,
  hosobenhanid integer ,
  maubenhphamid integer,
  maubenhphamphieutype integer ,
  servicepriceid_master integer ,
  thuockhobanle integer ,
  doituongbenhnhanid integer ,
  loaidoituong_org integer ,
  loaidoituong_org_remark text,
  loaidoituong integer ,
  loaiduyetbhyt integer ,
  loaidoituong_remark text,
  loaidoituong_userid integer ,
  departmentid integer ,
  departmentgroupid integer ,
  servicepricecode text,
  servicepricename text,
  servicepricename_nhandan text,
  servicepricename_bhyt text,
  servicepricename_nuocngoai text,
  servicepricedate timestamp without time zone,
  servicepricestatus integer,
  servicepricedoer text,
  servicepricecomment text,
  servicepricemoney double precision,
  servicepricemoney_nhandan double precision,
  servicepricemoney_bhyt double precision,
  servicepricemoney_nuocngoai double precision,
  servicepricemoney_bhyt_tra double precision,
  servicepricemoney_miengiam double precision,
  servicepricemoney_danop double precision,
  servicepricemoney_miengiam_type integer ,
  billid_thutien integer ,
  billid_hoantien integer ,
  billid_clbh_thutien integer ,
  billid_clbh_hoantien integer ,
  billaccountid integer ,
  soluong double precision,
  soluongbacsi double precision,
  huongdansudung text,
  version timestamp without time zone,
  loaipttt integer ,
  soluongquyettoan double precision ,
  servicepriceid_xuattoan double precision ,
  daduyetthuchiencanlamsang integer ,
  sync_flag integer,
  update_flag integer,
  servicepricemoney_bhyt_danop double precision,
  servicepricemoney_damiengiam double precision,
  loaidoituong_xuat integer,
  servicepricemoney_tranbhyt double precision,
  servicepricebhytdinhmuc text,
  servicepricebhytquydoi text,
  servicepricebhytquydoi_tt text,
  bhyt_groupcode text,
  huongdanphathuoc text,
  servicepriceid_org integer,
  lankhambenh integer,
  vitrisinhthiet text,
  somanhsinhthiet text,
  stt_theodoithuoc integer,
  chiphidauvao double precision,
  chiphimaymoc double precision,
  chiphipttt double precision,
  mayytedbid integer,
  loaingaygiuong integer,
  servicepriceid_thanhtoanrieng integer,
  stenphuthuoc integer,
  duyetpttt_stt integer,
  duyetpttt_date timestamp without time zone,
  duyetpttt_usercode text,
  duyetpttt_username text,
  bhyt_pttt integer)  
  
  
  
  
  
  
  